### ISSUE TITLE
Error when using "Reschedule cards" and FSRS4Anki Helper

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#1]
**Describe the bug**
When I try to reschedule cards I get an error.

**To Reproduce**
1. Install FSRS4Anki Helper
2. Use scheduler version: v3.0.0
3. Go to Tools -> Reschedule cards

**Expected behavior**
There should be no error when rescheduling cards.

**Environment**
 - Anki version: 2.1.55
 - OS: Windows 10
 - Scheduler version: v3.0.0

**Additional context**
Debug info:

Anki 2.1.55 (6944210f) Python 3.9.7 Qt 6.3.2 PyQt 6.3.1
Platform: Windows-10-10.0.19042
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-04 22:25:36

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 87, in reschedule
    d, s, r) if rating > 1 else scheduler.next_forget_stability(d, s, r)
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\759844606\reschedule.py", line 33, in next_forget_stability
    return self.w[9] * math.pow(d, self.w[10]) * math.pow(s, self.w[11]) * math.exp((1 - r) * self.w[12])
ValueError: math domain error

**Comment by L-M-Sherlock** [comment]
Can you give me the scheduler code that you use?

**Comment by Expertium** [comment]
```
// FSRS4Anki v3.0.0 Scheduler
set_version();
// The latest version will be released on https://github.com/open-spaced-repetition/fsrs4anki

// Default parameters of FSRS4Anki for global
var w = [0.1008, 0.7749, 3.6272, -1.311, -1.7187, 0.0301, 1.4735, -0.0921, 0.6985, 1.5923, -0.5809, 0.8169, 1.7466];
// The above parameters can be optimized via FSRS4Anki optimizer.

// User's custom parameters for global
let requestRetention = 0.8; // recommended setting: 0.8 ~ 0.9
let maximumInterval = 3650;
let easyBonus = 1.5;
let hardInterval = 1.2;

const ratings = {
  "again": 1,
  "hard": 2,
  "good": 3,
  "easy": 4
};

debugger;

// get the name of the card's deck
// need add <div id=deck deck_name="{{Deck}}"></div> to your card's front template
if (document.getElementById("deck") !== null) {
    const deck_name = document.getElementById("deck").getAttribute("deck_name");
    // parameters for a specific deck
    if (deck_name == "Kek") {
        var w = [1.1475, 1.401, 5.1483, -1.4221, -1.2282, 0.035, 1.4668, -0.1286, 0.7539, 1.9671, -0.2307, 0.32, 0.9451];
        // User's custom parameters for the specific deck
        requestRetention = 0.8;
        maximumInterval = 3650;
        easyBonus = 1.5;
        hardInterval = 1.2;
    // parameters for a deck's all sub-decks
    } else if (deck_name.startsWith("Main::English")) {
        var w = [0.6017, 1.097, 4.9402, -1.4763, -1.3786, 0.0147, 1.7209, -0.0282, 1.0052, 1.8154, -0.3572, 0.7001, 1.1472];
        // User's custom parameters for sub-decks
        requestRetention = 0.80;
        maximumInterval = 3650;
        easyBonus = 1.5;
        hardInterval = 1.2;
    } else if (deck_name.startsWith("Main::Japanese::Anime")) {
        var w = [1.1525, 1.3282, 4.3989, -0.8688, -1.131, 0.1189, 2.2486, -0.0118, 1.4999, 2.1524, -0.0826, 0.3843, 1.1415];
        // User's custom parameters for sub-decks
        requestRetention = 0.80;
        maximumInterval = 3650;
        easyBonus = 1.5;
        hardInterval = 1.2;
    } else if (deck_name.startsWith("Main::Japanese")) {
        var w = [0.1441, 0.4028, 4.5709, -1.5001, -1.5579, 0.0819, 1.4814, -0.1772, 0.7382, 1.6688, -0.5218, 0.89, 1.2454];
        // User's custom parameters for sub-decks
        requestRetention = 0.80;
        maximumInterval = 1825;
        easyBonus = 1.5;
        hardInterval = 1.2;
    } else if (deck_name.startsWith("Main::Geography")) {
        var w = [0.7681, 0.7755, 5.2104, -1.264, -1.2245, 0.0639, 1.1578, -0.1344, 0.4565, 1.7617, -0.4245, 0.5836, 1.2454];
        // User's custom parameters for sub-decks
        requestRetention = 0.80;
        maximumInterval = 1825;
        easyBonus = 1.5;
        hardInterval = 1.2;
    } else if (deck_name.startsWith("Main::Science")) {
        var w = [0.8073, 0.8851, 4.7079, -1.1674, -1.1728, 0.0324, 1.3492, -0.0128, 0.6251, 1.7459, -0.4496, 0.6793, 1.0997];
        // User's custom parameters for sub-decks
        requestRetention = 0.80;
        maximumInterval = 1095;
        easyBonus = 1.5;
        hardInterval = 1.2;
    } else if (deck_name.startsWith("Main::Misc")) {
        var w = [0.9765, 0.9822, 5.0297, -1.0693, -1.022, 0.0515, 1.4498, -0.1998, 0.7495, 2.0555, -0.1442, 0.2884, 1.0987];
        // User's custom parameters for sub-decks
        requestRetention = 0.95;
        maximumInterval = 90;
        easyBonus = 1.3;
        hardInterval = 1.2;
    }
}

// auto-calculate intervalModifier
const intervalModifier = Math.log(requestRetention) / Math.log(0.9);

// For new cards
if (is_new()) {
    init_states();
    states.easy.normal.review.scheduledDays = constrain_interval(customData.easy.s);
// For learning/relearning cards
} else if (is_learning()) {
    // Init states if the card didn't contain customData
    if (is_empty()) {
        init_states();
    }
    const good_interval = constrain_interval(customData.good.s);
    const easy_interval = Math.max(constrain_interval(customData.easy.s * easyBonus), good_interval + 1);
    if (states.good.normal?.review) {
        states.good.normal.review.scheduledDays = good_interval;
    }
    if (states.easy.normal?.review) {
        states.easy.normal.review.scheduledDays = easy_interval;
    }
// For review cards
} else if (is_review()) {
    // Convert the interval and factor to stability and difficulty if the card didn't contain customData
    if (is_empty()) {
        convert_states();
    }

    const interval = states.current.normal?.review.elapsedDays ? states.current.normal.review.elapsedDays : states.current.filtered.rescheduling.originalState.review.elapsedDays;
    const last_d = customData.again.d;
    const last_s = customData.again.s;
    const retrievability = Math.exp(Math.log(0.9) * interval / last_s);
    const lapses = states.again.normal?.relearning.review.lapses ? states.again.normal.relearning.review.lapses : states.again.filtered.rescheduling.originalState.relearning.review.lapses;

    customData.again.d = next_difficulty(last_d, "again");
    customData.again.s = next_forget_stability(customData.again.d, last_s, retrievability);

    customData.hard.d = next_difficulty(last_d, "hard");
    customData.hard.s = next_recall_stability(customData.hard.d, last_s, retrievability);

    customData.good.d = next_difficulty(last_d, "good");
    customData.good.s = next_recall_stability(customData.good.d, last_s, retrievability);

    customData.easy.d = next_difficulty(last_d, "easy");
    customData.easy.s = next_recall_stability(customData.easy.d, last_s, retrievability);

    const hard_interval = constrain_interval(last_s * hardInterval);
    const good_interval = Math.max(constrain_interval(customData.good.s), hard_interval + 1);
    const easy_interval = Math.max(constrain_interval(customData.easy.s * easyBonus), good_interval + 1);

    if (states.hard.normal?.review) {
        states.hard.normal.review.scheduledDays = hard_interval;
    }
    if (states.good.normal?.review) {
        states.good.normal.review.scheduledDays = good_interval;
    }
    if (states.easy.normal?.review) {
        states.easy.normal.review.scheduledDays = easy_interval;
    }
}

function constrain_difficulty(difficulty) {
    return Math.min(Math.max(difficulty.toFixed(2), 1), 10);
}

function constrain_interval(interval) {
    return Math.min(Math.max(Math.round(interval * intervalModifier), 1), maximumInterval);
}

function next_difficulty(d, rating) {
    let next_d = d + w[4] * (ratings[rating] - 3);
    return constrain_difficulty(mean_reversion(w[2], next_d));
}

function mean_reversion(init, current) {
    return w[5] * init + (1 - w[5]) * current;
}

function next_recall_stability(d, s, r) {
    return +(s * (1 + Math.exp(w[6]) *
    (11 - d) *
    Math.pow(s, w[7]) *
    (Math.exp((1 - r) * w[8]) - 1))).toFixed(2);
}

function next_forget_stability(d, s, r) {
    return +(w[9] * Math.pow(d, w[10]) * Math.pow(
        s, w[11]) * Math.exp((1 - r) * w[12])).toFixed(2);
}

function init_states() {
    customData.again.d = init_difficulty("again");
    customData.again.s = init_stability("again");
    customData.hard.d = init_difficulty("hard");
    customData.hard.s = init_stability("hard");
    customData.good.d = init_difficulty("good");
    customData.good.s = init_stability("good");
    customData.easy.d = init_difficulty("easy");
    customData.easy.s = init_stability("easy");
}

function init_difficulty(rating) {
    return +(w[2] + w[3] * (ratings[rating] - 3)).toFixed(2);
}

function init_stability(rating) {
    return +(w[0] + w[1] * (ratings[rating] - 1)).toFixed(2);
}

function convert_states() {
    const scheduledDays = states.current.normal ? states.current.normal.review.scheduledDays : states.current.filtered.rescheduling.originalState.review.scheduledDays;
    const easeFactor = states.current.normal ? states.current.normal.review.easeFactor : states.current.filtered.rescheduling.originalState.review.easeFactor;
    const old_s = +Math.max(scheduledDays, 0.1).toFixed(2);
    const old_d = constrain_difficulty(11 - (easeFactor - 1) / (Math.exp(w[6]) * Math.pow(old_s, w[7]) * (Math.exp(0.1 * w[8]) - 1)))
    customData.again.d = old_d;
    customData.again.s = old_s;
    customData.hard.d = old_d;
    customData.hard.s = old_s;
    customData.good.d = old_d;
    customData.good.s = old_s;
    customData.easy.d = old_d;
    customData.easy.s = old_s;
}

function is_new() {
    if (states.current.normal?.new !== undefined) {
        if (states.current.normal?.new !== null) {
            return true;
        }
    }
    if (states.current.filtered?.rescheduling?.originalState !== undefined) {
        if (Object.hasOwn(states.current.filtered?.rescheduling?.originalState, 'new')) {
            return true;
        }
    } 
    return false;
}

function is_learning() {
    if (states.current.normal?.learning !== undefined) {
        if (states.current.normal?.learning !== null) {
            return true;
        }
    }
    if (states.current.filtered?.rescheduling?.originalState !== undefined) {
        if (Object.hasOwn(states.current.filtered?.rescheduling?.originalState, 'learning')) {
            return true;
        }
    }
    if (states.current.normal?.relearning !== undefined) {
        if (states.current.normal?.relearning !== null) {
            return true;
        }
    }
    if (states.current.filtered?.rescheduling?.originalState !== undefined) {
        if (Object.hasOwn(states.current.filtered?.rescheduling?.originalState, 'relearning')) {
            return true;
        }
    }
    return false;
}

function is_review() {
    if (states.current.normal?.review !== undefined) {
        if (states.current.normal?.review !== null) {
            return true;
        }
    }
    if (states.current.filtered?.rescheduling?.originalState !== undefined) {
        if (Object.hasOwn(states.current.filtered?.rescheduling?.originalState, 'review')) {
            return true;
        }
    }
    return false;
}

function is_empty() {
    return !customData.again.d | !customData.again.s | !customData.hard.d | !customData.hard.s | !customData.good.d | !customData.good.s | !customData.easy.d | !customData.easy.s;
}

function set_version() {
    const version = "3.0.0";
    customData.again.v = version;
    customData.hard.v = version;
    customData.good.v = version;
    customData.easy.v = version;
}
```

**Comment by L-M-Sherlock** [comment]
The parameters seem normal. I need to reproduce this bug with your collection backup. Could share it with me?

**Comment by Expertium** [comment]
How exactly do I share my collection? Just export a .colpkg file?

**Comment by L-M-Sherlock** [comment]
Yes, .colpkg file is enough.

**Comment by Expertium** [comment]
I found something **REALLY** weird.
So I deleted a deck that was related to incremental reading (idk, maybe the cards themselves somehow cause problems?) and tried again. I still get an error. Now here is the weird part - the add-on does reschedule cards, but in a **non-deterministic** way. Every time I reschedule cards I get a different number of due cards, any number from 20 to 1000+. I then revert back, reschedule again, and the number is different every single time. I cannot even begin to imagine what could be causing this.
Alright, here's the collection file: https://drive.google.com/file/d/1sYg-o8T7dY1bqUfX8am_Mjjog5P7NvOt/view?usp=sharing

**Comment by L-M-Sherlock** [comment]
I fix that bugs in the latest version: https://ankiweb.net/shared/info/759844606

**Comment by L-M-Sherlock** [comment]
BTW, processing 80k+ cards needs a little time.

**Comment by Expertium** [comment]
Alright, seems to be fixed.
And it gives me 3000+ due cards. Well...guess I won't be rescheduling for now :D
