### ISSUE TITLE
NameError when attempting to undo rescheduling. 

### ISSUE THREAD

**Issue by soccerwithag** [open-spaced-repetition/fsrs4anki-helper#132]
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-06-15 03:16:25
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/home/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 46, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did))
  File "/Users/home/Library/Application Support/Anki2/addons21/759844606/reset.py", line 17, in reset
    if not askUser("""Undo all changes made by rescheduling.
NameError: name 'askUser' is not defined

**Comment by L-M-Sherlock** [comment]
Please check the update of the add-on.
