### ISSUE TITLE
[bug] Error when rescheduling

### ISSUE THREAD

**Issue by tnyjcb** [open-spaced-repetition/fsrs4anki-helper#171]
Using the latest version of the add-on and the scheduler. Anki 2.1.65 Qt6. Completely unable to reschedule but postpone, advance, disperse, etc. all seem to work fine.

```Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-07-27 23:07:15
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/Users/jcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 141, in on_done
    tooltip(future.result())
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/jcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 153, in <lambda>
    fut = mw.taskman.run_in_background(lambda: reschedule_background(did, recent, filter_flag, filtered_cids), on_done)
  File "/Users/jcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 205, in reschedule_background
    card = reschedule_card(cid, fsrs, rollover, version, cur_deck_param)
  File "/Users/jcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 283, in reschedule_card
    again_s = fsrs.next_forget_stability(fsrs.next_difficulty(d, 1), s, r)
  File "/Users/jcb/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 93, in next_forget_stability
    (math.pow(s + 1, self.w[13]) - 1) *
IndexError: list index out of range
```

**Comment by L-M-Sherlock** [comment]
What's your parameters of FSRS?

**Comment by tnyjcb** [comment]
```{
    "deckName": "global config for FSRS4Anki",
    "w": [2.3149, 2.4162, 4.8896, -1.2341, -1.1157, 0.05, 1.6933, -0.15, 1.0931, 2.2164, -0.1319, 0.4609, 1.2468],
    "requestRetention": 0.9,
    "maximumInterval": 36500,
  },
  {
    "deckName": "JP::Vocab",
    "w": [1.8671, 1.9177, 4.9551, -0.8114, -0.7624, 0.05, 1.508, -0.15, 0.9072, 2.2035, -0.024, 0.4141, 1.2186],
    "requestRetention": 0.89,
    "maximumInterval": 36500,
  },
  {
    "deckName": "JP::Listening",
    "w": [1.908, 1.9118, 4.8491, -0.7486, -0.7457, 0.05, 1.56, -0.15, 0.9569, 2.2249, -0.01, 0.4146, 1.2291],
    "requestRetention": 0.91,
    "maximumInterval": 36500,
  }```

These haven't changed for a month or so. The issue is only occurring since updating the add-on. Last time I updated would have been before 10 July so maybe two or three versions ago. I updated the custom scheduling at the same time.

**Comment by L-M-Sherlock** [comment]
The old parameters of FSRSv3 is incompatible with FSRSv4. I recommend you to re-optimize your decks or use the default parameters.

**Comment by tnyjcb** [comment]
Thanks for explaining. Updated with the new parameters and it works again.
