### ISSUE TITLE
[BUG] Reschedule upon failed rep causes an error

### ISSUE THREAD

**Issue by revolverXD** [open-spaced-repetition/fsrs4anki-helper#207]
**Describe the bug**
Get an error when I fail a rep

**To Reproduce**
1. Do your reps normally
2. Press 1 to indicate failed rep
3. Get the following error:
`Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-27 12:21:18
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 460, in after_answer
  File "aqt.reviewer", line 473, in _after_answering
  File "_aqt.hooks", line 3982, in __call__
  File "/home/david/.local/share/Anki2/addons21/759844606/schedule/__init__.py", line 9, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease, undo_entry)
  File "/home/david/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 299, in disperse_siblings_when_review
    siblings = get_siblings_when_review(card)
  File "/home/david/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 270, in get_siblings_when_review
    return siblings_dict[nid]
UnboundLocalError: local variable 'nid' referenced before assignment
`

**Expected behavior**
As before the rep should reschedule without error

**Screenshots**

**Environment**
 - Anki version: 2.1.65 
 - OS: Linux
 - Scheduler version:  v3
 - Optimizer version: Not sure
 - Simulator version: Not sure

**Additional context**

**Comment by revolverXD** [comment]
I played around with the options and found out that disabling:
Auto disperse siblings after review and sync
Stops the issue from happening.

**Comment by L-M-Sherlock** [comment]
My fault. I wrote a bug in the latest version. But I'm outside now. I will fix it in 3~4 hours.

**Comment by revolverXD** [comment]
Thank you for your hard work.
