### ISSUE TITLE
[BUG] Error in disperse_siblings.py while reviewind

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki-helper#208]
**Describe the bug**

While reviewing I've put "Again" answer on the card and got the following stack trace:
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-27 10:49:21

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.operations", line 125, in wrapped_done
  File "aqt.reviewer", line 460, in after_answer
  File "aqt.reviewer", line 473, in _after_answering
  File "_aqt.hooks", line 3982, in __call__
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\__init__.py", line 9, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease, undo_entry)
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 299, in disperse_siblings_when_review
    siblings = get_siblings_when_review(card)
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 270, in get_siblings_when_review
    return siblings_dict[nid]
UnboundLocalError: local variable 'nid' referenced before assignment

**To Reproduce**
1. Go to cards reviewing
2. Answer card "Again"
3. See error

It happened on one card only, the other 60 reviews during this session were ok.

**Expected behavior**

**Screenshots**

**Environment**
 - Anki version: 2.1.65
 - OS: Windows-10-10.0.19045
 - Scheduler version: v4.3.0 Scheduler Qt6

**Additional context**

**Comment by L-M-Sherlock** [comment]
My fault. I wrote a bug in the latest version. But I'm outside now. I will fix it in 3~4 hours.

**Comment by szalejot** [comment]
Thank you for fast response.
Glad it's not somethings serious 😊
