### ISSUE TITLE
[BUG] "ValueError: Value out of range" in disperse_siblings.py, disperse_siblings_backgroud

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki-helper#215]
**Describe the bug**
Error message while dispersing siblings:

Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-04 15:54:53

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 88, in on_done
    tooltip(future.result())
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 92, in <lambda>
    mw.taskman.run_in_background(lambda: disperse_siblings_backgroud(did, filter_flag, filtered_nid_string, text_from_reschedule), on_done)
  File "C:\Users\michal\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 135, in disperse_siblings_backgroud
    mw.col.update_card(card)
  File "anki.collection", line 524, in update_card
  File "anki.collection", line 518, in update_cards
  File "anki.collection", line 518, in <listcomp>
  File "anki.cards", line 99, in _to_backend_card
  File "google.protobuf.internal.python_message", line 542, in init
  File "google.protobuf.internal.python_message", line 683, in field_setter
  File "google.protobuf.internal.type_checkers", line 166, in CheckValue
ValueError: Value out of range: -242

**To Reproduce**
Either auto disperse after sync or dispersing all manually.

**Expected behavior**
No error

**Screenshots**
none

**Environment**
 - Anki version: 2.1.65
 - OS: Windows
 - Scheduler version: v4.5.6 Scheduler Qt6

**Additional context**

**Comment by L-M-Sherlock** [comment]
Could you give me a deck to reproduce this bug?

**Comment by szalejot** [comment]
Here is the link to exported collection, without media: https://drive.google.com/file/d/1Utxetsb6uOFoAMc6L_UqHNZoXx-yaM4f/view?usp=drivesdk

**Comment by L-M-Sherlock** [comment]
The affected card has many manual reset:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/11c80bd1-19f4-494f-91bf-af3a0f8afb63)

I'm finding the solution.

**Comment by L-M-Sherlock** [comment]
Please update your add-on. The latest version should solve this bug.
