### ISSUE TITLE
Syncing error

### ISSUE THREAD

**Issue by chrislongros** [open-spaced-repetition/fsrs4anki-helper#242]
(https://forums.ankiweb.net/t/fsrs-helper-syncing-error/34820/2)

Debug info:
Anki 23.10 (c2b1ab5e) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.5.4-1-MANJARO-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-09-21 16:34:38

Caught exception:
Traceback (most recent call last):
  File "/home/chris/ankidev/qt/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/home/chris/ankidev/qt/aqt/taskman.py", line 82, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
  File "/home/chris/ankidev/qt/aqt/taskman.py", line 102, in wrapped_done
    on_done(fut)
  File "/home/chris/ankidev/qt/aqt/sync.py", line 100, in on_future_done
    mw.col.db.begin()
  File "/home/chris/ankidev/pylib/anki/dbproxy.py", line 36, in begin
    self._backend.db_begin()
  File "/home/chris/ankidev/pylib/anki/_backend.py", line 100, in db_begin
    return self._db_command(dict(kind="begin"))
  File "/home/chris/ankidev/pylib/anki/_backend.py", line 116, in _db_command
    raise backend_exception_to_pylib(err)
anki.errors.DBError: DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"cannot start a transaction within a transaction\"))", kind: Other }

**Comment by L-M-Sherlock** [comment]
The helper add-on doesn't support Anki 23.10, so how do you enable it?
