### ISSUE TITLE
[BUG] disperse_siblings_when_review failing on Anki 23.10 Beta 2

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki-helper#247]
**Describe the bug**
While reviewing with siblings disperse turned on error message appears.

**Expected behavior**
To not produce an error.

**Environment**
 - Anki version: 23.10 Beta 1
 - OS: macOS 13.6

**Additional context**

Debug info:
Anki 23.10 (2ab8aa00) Python 3.9.15 Qt 6.5.2 PyQt 6.5.0
Platform: macOS-13.6-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-25 09:09:02
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 463, in after_answer
  File "aqt.reviewer", line 476, in _after_answering
  File "_aqt.hooks", line 4111, in __call__
  File "/Users/mherma/Library/Application Support/Anki2/addons21/759844606/schedule/__init__.py", line 6, in reschedule_and_disperse_siblings_when_review
    disperse_siblings_when_review(reviewer, card, ease)
  File "/Users/mherma/Library/Application Support/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 340, in disperse_siblings_when_review
    "m": deck_config["rev"]["maxIvl"],
KeyError: 'rev'

**Comment by szalejot** [comment]
I've just upgraded Anki to 23.10 Beta 2, but issue still persists.

**Comment by L-M-Sherlock** [comment]
Please check updates for the add-on.

**Comment by szalejot** [comment]
After add-on update there is no error occurring.
