### ISSUE TITLE
[BUG] "ValueError: math domain error" with some cards

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#252]
**Describe the bug**
I just ~~tweaked a few requestRetentions (changes like 0.82→0.819),~~ updated the addon and chose Reschedule.
Shortly after that, this happened:

```python
Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/home/user/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 256, in on_done
    tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/home/user/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 277, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "/home/user/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 354, in reschedule_background
    card = reschedule_card(cid, fsrs, rollover, cur_deck_param)
  File "/home/user/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 405, in reschedule_card
    s, d = fsrs.memory_state_from_sm2(
  File "/home/user/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 243, in memory_state_from_sm2
    * math.pow(stability, -self.w[9])
ValueError: math domain error
```

**Environment**
 - Anki version: 2.1.66
 - OS: Debian GNU/Linux
 - Scheduler version: 4.5.6?

**Comment by L-M-Sherlock** [comment]
Could you share the affected card with me? Or just send the deck file with scheduling info.

**Comment by aleksejrs** [comment]
[fsrs4anki-helper-issues-252.apkg.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12749455/fsrs4anki-helper-issues-252.apkg.zip)

**Comment by L-M-Sherlock** [comment]
<img width="800" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/bf87fc3f-2c78-4b0b-b59b-b56be9c65e6f">

This revlog is weird, because its interval is 0 second. I will fix it soon.

**Comment by L-M-Sherlock** [comment]
Please check update. The latest commit 7b969caae525dc075e06a3fba5c21fbc76d3404f should have solved this issue.

**Comment by aleksejrs** [comment]
Thanks, everything rescheduled successfully.
