### ISSUE TITLE
[BUG] beta5 breaks the add-on

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#266]
**Describe the bug**
```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨FSRS4Anki Helper⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 239, in loadAddons
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 14, in <module>
    from .browser.browser import init_browser
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\browser\browser.py", line 9, in <module>
    from .custom_columns import (
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\browser\custom_columns.py", line 50, in <module>
    class TargetRetrievabilityColumn(CustomColumn):
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\759844606\browser\custom_columns.py", line 51, in TargetRetrievabilityColumn
    builtin_column = Column(
ValueError: Protocol message Column has no "sorting" field.
```
⁩

**To Reproduce**
1. Install 23.10beta5
2. Try to launch Anki with the helper add-on
3. See error

**Comment by cjdduarte** [comment]
this error occurs here too.

**Comment by L-M-Sherlock** [comment]
I can't test it, because beta5 can't work on my Mac. I recommend disabling the add-on in beta5.
