### ISSUE TITLE
[BUG]  'NoneType' object has no attribute 'result'

### ISSUE THREAD

**Issue by chieh0958** [open-spaced-repetition/fsrs4anki-helper#275]
**Describe the bug**
1.
Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.sync", line 119, in on_future_done
  File "aqt.main", line 1024, in on_collection_sync_finished
  File "_aqt.hooks", line 4999, in __call__
  File "C:\Users\N\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 57, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids))
  File "C:\Users\N\AppData\Roaming\Anki2\addons21\759844606\sync_hook.py", line 50, in auto_reschedule
    return fut.result()
AttributeError: 'NoneType' object has no attribute 'result'

2. Anki show "please enable FSRS first" at the bottom left corner.

**To Reproduce**
1. Addon shows the bug when I turn on "Auto reschedule cards reviewed on other devices after sync"
2. I use FSRS Scheduler Code and turn off the integrated FSRS.

**Screenshots**
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/100467749/1a07a096-0d89-4e60-9e5f-cd5a0fcc37f3)

**Environment**
 - Anki version: Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
 - OS: win 10
 - Scheduler version: v4.5.6 Scheduler Qt6

**Comment by L-M-Sherlock** [comment]
The helper doesn't support custom scheduling version in Anki 23.10.

**Comment by L-M-Sherlock** [comment]
Please read the Description of the add-on: https://ankiweb.net/shared/info/759844606

Requirements
For Anki version in 2.1.55 - 2.1.66
Enable V3 Scheduler
FSRS4Anki scheduler version >= 3.0.0
For Anki version >= 23.10
Enable FSRS
Remove FSRS4Anki scheduler code
