### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LeonardoDEJE** [open-spaced-repetition/fsrs4anki-helper#281]
Error message when using anki helper in deck [nations ](https://ankiweb.net/shared/info/123449169) with anki 23.10: (portuguese message)

Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-25 08:38:10
Extensões possivelmente envolvidas: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "aqt.taskman", line 102, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 434, in after_answer
  File "aqt.reviewer", line 444, in _after_answering
  File "_aqt.hooks", line 4134, in __call__
  File "C:\Users\eu\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 349, in disperse_siblings_when_review
    siblings = get_siblings_when_review(card)
  File "C:\Users\eu\AppData\Roaming\Anki2\addons21\759844606\schedule\disperse_siblings.py", line 68, in get_siblings_when_review
    siblings = mw.col.db.all(
  File "anki.dbproxy", line 71, in all
  File "anki.dbproxy", line 65, in _query
  File "anki._backend", line 96, in db_query
  File "anki._backend", line 120, in _db_command
anki.errors.DBError: DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"malformed JSON\"))", kind: Other }

**Comment by L-M-Sherlock** [comment]
Duplicate of #276.
