### ISSUE TITLE
[BUG] IndexError: list index out of range in get_last_review_date if the card was rescheduled and has no reviews

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#282]
# Error occurs with this card:

Added	2023-10-22
First Review	2023-10-22
Latest Review	2023-10-22
Due	2023-10-22
Interval	⁨1⁩ day
Stability	⁨10⁩ hours
Difficulty	84%
Retrievability	100%
Reviews	0
Lapses	0
Card ID	1698005383968
Custom Data	v=reschedule seed=1386

The only history entry:
Date 2023-10-22 @ 23:09
Type Manual
Rating 0
Interval ⁨1⁩ day
Ease 377%
Time ⁨0⁩s

# Does not occur with this card:

Added	2023-08-05
Due	2023-10-22
Interval	⁨8.13⁩ months
Ease	402.1%
Reviews	13
Lapses	2
Card ID	1691185791455

No history entries.

# Error

```
Anki 23.10 (3394ab02) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.5.0-2-amd64-x86_64-with-glibc2.37
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-26 07:53:07
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "/home/anki/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 131, in on_done
    tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/home/anki/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 152, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "/home/anki/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 225, in reschedule_background
    card = reschedule_card(cid, fsrs, filter_flag)
  File "/home/anki/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 273, in reschedule_card
    card = update_card_due_ivl(card, new_ivl)
  File "/home/anki/.local/share/Anki2/addons21/759844606/utils.py", line 66, in update_card_due_ivl
    last_review_date = get_last_review_date(card)
  File "/home/anki/.local/share/Anki2/addons21/759844606/utils.py", line 57, in get_last_review_date
    last_revlog = list(filter(lambda x: x.button_chosen >= 1, revlogs))[0]
IndexError: list index out of range
```

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13174334/fsrs4anki-helper.zip)

**Comment by aleksejrs** [comment]
Works. thanks. Disperse also worked.
