### ISSUE TITLE
[BUG] OverflowError: date value out of range when rescheduling a specific deck

### ISSUE THREAD

**Issue by parfait8566** [open-spaced-repetition/fsrs4anki-helper#286]
**Describe the bug**
Error when rescheduling a specific deck (doesn't happen when rescheduling other decks).

**Environment**
 - Anki version: 23.10 RC2
 - OS: Windows 11
 - Optimizer version: v4.10.1

**Additional context**

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (7428ecad) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22624
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-27 09:09:35
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 138, in _on_closures_pending
  File "aqt.taskman", line 82, in <lambda>
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 131, in on_done
    tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 152, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 225, in reschedule_background
    card = reschedule_card(cid, fsrs, filter_flag)
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 266, in reschedule_card
    new_ivl = fsrs.next_interval(s, fsrs.dr, fsrs.max_ivl)
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 96, in next_interval
    new_interval = self.apply_fuzz(9 * stability * (1 / retention - 1))
  File "C:\Users\parf\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 77, in apply_fuzz
    due_date = datetime.now() + timedelta(days=day_offset)
OverflowError: date value out of range

```

**Comment by L-M-Sherlock** [comment]
Could you send the deck file with scheduling info to me? It would help me debug.

**Comment by parfait8566** [comment]
> Could you send the deck file with scheduling info to me? It would help me debug.

[test deck.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13188496/test.deck.zip)

**Comment by L-M-Sherlock** [comment]
<img width="821" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/6621d802-6008-4bd0-af95-6825bd13553d">

The stability is incorrect. Could you tell me what did you do with FSRS?

**Comment by L-M-Sherlock** [comment]
<img width="821" alt="image" src="https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/f428b00e-b464-46c8-a15c-732ba117f86f">

You have some weird cards. Their revlogs are manually rescheduled. Do you know why these cards have these revlogs?

**Comment by L-M-Sherlock** [comment]
@parfait8566, I recommend `Forget` these cards to reset the incorrect data.

**Comment by parfait8566** [comment]
> You have some weird cards. Their revlogs are manually rescheduled. Do you know why these cards have these revlogs?

I needed to have some cards in the deck without the need to actually review them so I rescheduled them to the distant future.

**Comment by user1823** [comment]
You could have suspended them instead.
