### ISSUE TITLE
[BUG] on postponing: IndexError: list index out of range in get_last_review_date if the card was rescheduled and has no reviews

### ISSUE THREAD

**Issue by aleksejrs** [open-spaced-repetition/fsrs4anki-helper#290]
Same as https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/282, but on postponing (Anki 23.10rc3)

```
Debug info:
Anki 23.10 (ef6f533c) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.5.0-2-amd64-x86_64-with-glibc2.37
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-30 00:28:16
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/home/anki/.local/share/Anki2/addons21/759844606/__init__.py", line 55, in <lambda>
    a.triggered.connect(lambda b, did=did: fun(did))
  File "/home/anki/.local/share/Anki2/addons21/759844606/schedule/postpone.py", line 101, in postpone
    last_review = get_last_review_date(card)
  File "/home/anki/.local/share/Anki2/addons21/759844606/utils.py", line 57, in get_last_review_date
    last_revlog = list(filter(lambda x: x.button_chosen >= 1, revlogs))[0]
IndexError: list index out of range
```

```
Added	2023-10-17
First Review	2023-10-17
Latest Review	2023-10-17
Due	2023-10-29
Position	2000007
Interval	⁨12⁩ days
Stability	⁨12⁩ days
Difficulty	0%
Retrievability	100%
Reviews	0
Lapses	0
Card ID	1697563735329
Note ID	1697563735329
Custom Data	v=reschedule seed=9063
Date 2023-10-17 @ 20:28
Type Manual
Rating 0
Interval ⁨12⁩ days
Ease 377%
Time ⁨0⁩s
```

Also, Browser says Retrievability is 89% (but 100% above) and Target R is 90.00%, but Desired Retention in the preset is 0.81 (did reschedule).

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13211291/fsrs4anki-helper.zip)

Could you help me test it?

**Comment by aleksejrs** [comment]
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/13211291/fsrs4anki-helper.zip)

Error does not appear on the copy of the profile on which it appeared just before applying that.
