### ISSUE TITLE
[BUG] 插件无法启用，系统是Windows for arm 22H2.

### ISSUE THREAD

**Issue by FEI352** [open-spaced-repetition/fsrs4anki-helper#291]
**Describe the bug**
插件无法启用，系统是Windows for arm 22H2.

**To Reproduce**
更新"anki-23.10-windows-qt6.exe"就弹出

---
# 插件启动失败

以下插件加载失败： ⁨

- [FSRS4Anki Helper](https://ankiweb.net/shared/info/759844606)⁩

这些插件需要更新至支持本版本的 Anki，请到「工具」>「插件」点击 检查更新 按钮来查看是否有可用的更新。

对于无可用更新的插件，您可以禁用或删除它们来阻止这条消息的出现。

---
（不过在我的x86 的机器上是正常的。

**调试日志**

---
Anki 23.10 (ef6f533c) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-31 09:35:28

When loading FSRS4Anki Helper:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\22242\AppData\Roaming\Anki2\addons21\759844606\__init__.py", line 15, in <module>
    from .browser.browser import init_browser
  File "C:\Users\22242\AppData\Roaming\Anki2\addons21\759844606\browser\browser.py", line 10, in <module>
    from .custom_columns import (
  File "C:\Users\22242\AppData\Roaming\Anki2\addons21\759844606\browser\custom_columns.py", line 51, in <module>
    class StabilityColumn(CustomColumn):
  File "C:\Users\22242\AppData\Roaming\Anki2\addons21\759844606\browser\custom_columns.py", line 52, in StabilityColumn
    builtin_column = Column(
ValueError: Protocol message Column has no "sorting" field.

---

**Environment**

 - Anki version: [anki-23.10-windows-qt6.exe]
 - OS: [windows11 for arm 22H2]
 - Helper的版本应该是最新的。

**Comment by L-M-Sherlock** [comment]
卸载插件，重新安装即可。
