### ISSUE TITLE
[BUG] Error on reviewing

### ISSUE THREAD

**Issue by matejdro** [open-spaced-repetition/fsrs4anki-helper#310]
**Describe the bug**

I just got this error after reviewing. It disappeared after restarting Anki, but I am reporting it just in case it is something actionable.

I am not using easy days feature (it is turned off).

**To Reproduce**
1. Open Anki
2. Start a review
3. Press any of the buttons (for example "Good")
4. See error:

```
Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 82, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 102, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.11/site-packages/aqt/operations/__init__.py", line 127, in wrapped_done
    self._success(result)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 434, in after_answer
    self._after_answering(ease)
  File "/usr/lib/python3.11/site-packages/aqt/reviewer.py", line 444, in _after_answering
    gui_hooks.reviewer_did_answer_card(self, self.card, ease)
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 4173, in __call__
    hook(reviewer, card, ease)
  File "/home/matejd/.local/share/Anki2/addons21/759844606/schedule/disperse_siblings.py", line 223, in disperse_siblings_when_review
    easy_days = config.easy_days
                ^^^^^^^^^^^^^^^^
  File "/home/matejd/.local/share/Anki2/addons21/759844606/configuration.py", line 46, in free_days
    return self.data[EASY_DAYS]
           ~~~~~~~~~^^^^^^^^^^^
KeyError: 'free_days'
```

**Environment**
```
Anki 23.10 (51a10f09) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-11-24 09:16:22
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩
```

**Comment by L-M-Sherlock** [comment]
These codes are unused, so I remove them.
