### ISSUE TITLE
[Question] [Bug?] My addon quite working for some reason 

### ISSUE THREAD

**Issue by lolnotadoc** [open-spaced-repetition/fsrs4anki-helper#363]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [ ] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [ ] I have searched for similar existing questions here

**Question**

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.sync", line 124, in on_future_done
  File "aqt.main", line 1057, in on_collection_sync_finished
  File "_aqt.hooks", line 5038, in __call__
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 93, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 51, in auto_reschedule
    texts.append(fut.result())
  File "concurrent.futures._base", line 446, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 148, in <lambda>
    lambda: reschedule_background(
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 174, in reschedule_background
    fsrs.p_obey_easy_days = p_obey_easy_days(
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/utils.py", line 189, in p_obey_easy_days
    return (7 - num_of_easy_days) / (
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 144, in on_done
    tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.sync", line 124, in on_future_done
  File "aqt.main", line 1057, in on_collection_sync_finished
  File "_aqt.hooks", line 5038, in __call__
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 93, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 51, in auto_reschedule
    texts.append(fut.result())
  File "concurrent.futures._base", line 446, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 148, in <lambda>
    lambda: reschedule_background(
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 174, in reschedule_background
    fsrs.p_obey_easy_days = p_obey_easy_days(
  File "/Users/michaelvalentine/Library/Application Support/Anki2/addons21/759844606/utils.py", line 189, in p_obey_easy_days
    return (7 - num_of_easy_days) / (
ZeroDivisionError: division by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T09:34, 'None', '']
Advanced Copy Fields ['1898445115', 2024-01-08T11:01, 'v0.4.01', '']
Advanced Review Bottom Bar ['1136455830', 2024-02-04T12:38, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-01-19T15:17, 'None', mod]
Audiovisual Feedback ['231569866', 2023-07-08T22:34, '0.8', mod]
Batch Editing ['291119185', 2023-10-25T19:38, 'None', '']
BetterSearch ['1052724801', 2023-06-15T15:44, 'None', '']
Browser MaximizeHide TableEditorSidebar ['1819291495', 2023-06-24T09:09, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-30T16:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-01-30T20:50, 'v0.11.5-beta', mod]
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T04:17, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-01-03T01:19, '6.18', mod]
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T10:58, 'None', '']
FSRS4Anki Helper ['759844606', 2024-02-08T08:06, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T14:17, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Learning Step and Review Interval Retention ['1949865265', 2024-01-06T11:48, 'None', '']
Localize Media ['1293255374', 2023-10-18T22:14, 'None', '']
Maximum image height and width in card editor ['229181581', 2021-07-23T01:01, 'None', '']
More Decks Stats and Time Left ['1556734708', 2023-09-24T09:08, 'None', '']
More Overview Stats ['2116130837', 2022-09-16T12:56, 'None', '']
New Cards Counter ['635082046', 2022-04-20T15:37, 'None', '']
PDF Exporter ['1442112168', 2022-11-16T14:23, 'None', '']
PDF Glossary Exporter ['pdf_glossary', 2019-08-19T07:35, 'None', '']
Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-19T23:40, 'None', '']
Remote Decks ['924929499', 2022-11-15T07:37, 'None', '']
Remove Cloze Button and Hotkey ['1966460736', 2022-05-21T05:29, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
Symbols ['1461102936', 2019-04-18T15:21, 'None', mod]
The KING of Study Timers ['907028815', 2022-04-20T13:14, 'None', '']
UpToDate Addon ['utd_anki_addon', 2023-05-08T10:16, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T13:28, 'None', '']
Wrapper meta-addon ['396502676', 2023-07-22T07:05, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T11:22, 'None', '']
batch create filtered decks ['1515706653', 2020-03-03T12:32, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T09:12, 'None', mod]
uworld_qid_to_anki_search ['607963104', 2023-01-18T15:20, 'None', '']

===IDs of active AnkiWeb add-ons===
1052724801 1135507717 1136455830 1210908941 1293255374 1374772155 1442112168 1461102936 1515706653 1556734708 1739176371 1771074083 1810938259 1819291495 1898445115 1898790263 1949865265 1966460736 2116130837 225180905 229181581 231569866 24411424 291119185 385888438 396502676 561945101 594329229 607963104 635082046 759844606 805891399 864545277 874215009 907028815 924929499 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiHub ['1322529746', 2024-02-01T16:46, 'None', '']

**Comment by aleksejrs** [comment]
Did you choose all the days to be easy?

**Comment by lolnotadoc** [comment]
Ahhhhhh you know what. I think I did. Thank you! I deleted the addon and
then re-uploaded the addon. Then changed the settings, or maybe it
automatically reset by itself? Either way, after 2 hours of messing around,
I figured it out.

**Comment by aleksejrs** [comment]
@L-M-Sherlock, it's still a bug that a Python error happens if all 7 days are Easy days.

**Comment by L-M-Sherlock** [comment]
> I think it's still a bug that a _Python_ error happens if all 7 days are Easy days.

It's invalid to set all 7 days as Easy Days. If they want to use Anki once a week, 6 days for Easy Days is enough.

**Comment by aleksejrs** [comment]
Right, maybe they should learn to read Python messages. But it isn't so obvious when Anki shows a dialog with "Copy Debug Info", and the message is in the debug info and in the terminal.

**Comment by L-M-Sherlock** [comment]
Fine. I will prevent users from setting 7 easy days to avoid this issue.

**Comment by aleksejrs** [comment]
There is a misspelling: it should be "specific", not "sepcific".
