### ISSUE TITLE
[BUG] Add-on Startup Failed

### ISSUE THREAD

**Issue by Akv2021** [open-spaced-repetition/fsrs4anki-helper#426]
The following add-ons failed to load: ⁨
[FSRS Helper Postpone Advance Load Balance Easy Days Disperse Siblings](https://ankiweb.net/shared/info/759844606)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.

Debug Info : 

Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

When loading FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/a/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 15, in <module>
    from .browser.browser import init_browser
  File "/Users/a/Library/Application Support/Anki2/addons21/759844606/browser/browser.py", line 10, in <module>
    from .custom_columns import (
  File "/Users/a/Library/Application Support/Anki2/addons21/759844606/browser/custom_columns.py", line 51, in <module>
    class StabilityColumn(CustomColumn):
  File "/Users/a/Library/Application Support/Anki2/addons21/759844606/browser/custom_columns.py", line 52, in StabilityColumn
    builtin_column = Column(
ValueError: Protocol message Column has no "sorting" field.

**Comment by L-M-Sherlock** [comment]
Please try to re-install this add-on.
