### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KevinJaques** [open-spaced-repetition/fsrs4anki-helper#465]
**Describe the bug**
When I ask it to reschedule all cards, it always complains "Please paste the code of FSRS4Anki into custom scheduling at the bottom of the deck options screen." Yeah, but I have. I pasted the installation code there, I pasted FSRS4Anki, I pasted FSRS4ANKI. After doing so, I hit save for each attempt. I tried quitting and relaunching for each attempt.
It also says that when I quit.
On my first quit, which might be before I had saved after putting the code into the custom scheduling, it reported an error and pointed out that fsrs4anki-helper was my only add-on, and so the only suspect.

**To Reproduce**
1. Tools menu: FRS4Anki Helper:Reschedule all cards"

**Expected behavior**
It's my first use, so I just expected it to show me a timer then report success.

**Screenshots**
If you want some, I can provide.

**Environment**
 - Anki version: [e.g. 2.1.55]: Version ⁨2.1.55 (01caec2a)⁩
Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
 - OS: [e.g. iOS] macOS Mojave 10.14.6
 - Scheduler version: [e.g. v1.0.0]: ??
 - Optimizer version: [e.g. v1.0.3]: ??
 - Simulator version: [e.g. v1.1.0]: ??

**Additional context**
I have turned on the 1st 4 options in fsrs4anki's menu.

**Comment by L-M-Sherlock** [comment]
Could you paste the code you pasted at the bottom of the deck options screen here?

**Comment by KevinJaques** [comment]
> Could you paste the code you pasted at the bottom of the deck options screen here?

Like I said, one time I pasted the installation code, '759844606', once I used 'FSRS4ANKI', and once I used FSRS4Anki. I will try that last one again, my best guess, and include a screen shot.

![image](https://github.com/user-attachments/assets/b253ed51-5a86-4073-8b09-05fc620093c6)

**Comment by L-M-Sherlock** [comment]
Do you follow this tutorial?

https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial2.md

**Comment by user1823** [comment]
If, for any reason (like incompatible add-ons), you can't update your Anki, follow the tutorial shared by L-M-Sherlock above.

However, if you can, I advise installing the latest version of Anki from https://apps.ankiweb.net/

Using FSRS in the latest version of Anki is much easier. Follow this tutorial for the built-in FSRS: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md

**Comment by KevinJaques** [comment]
> However, if you can, I advise installing the latest version of Anki from https://apps.ankiweb.net/

Thanks, but MacOS Mojave (x.14) is the last to support 32 bit apps so I am keeping my desktop machine at that level. And I think I have the latest anki that runs on Mojave.

**Comment by L-M-Sherlock** [comment]
OK. Do our suggestions resolve your problem?

**Comment by KevinJaques** [comment]
> If, for any reason (like incompatible add-ons), you can't update your Anki, follow the tutorial shared by L-M-Sherlock above.
> 
> However, if you can, I advise installing the latest version of Anki from https://apps.ankiweb.net/
> 
> Using FSRS in the latest version of Anki is much easier. Follow this tutorial for the built-in FSRS: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial.md



> Did you follow this tutorial?
> 
> https://github.com/open-spaced-repetition/fsrs4anki/blob/main/docs/tutorial2.md

No, I definitely did not. There is nothing on the add-on page to suggest a tutorial of any kind, and even if a diligent user like myself did check out the github page and looked at the tutorial, there was nothing in the tutorial to suggest using tutorial2.

However, thank you for the link, and now I have attempted to follow it.  It says to use Tools:Preferences... but that doesn't exist. So I used Anki: Preferences. It says to use ...Preferences:Review, but that doesn't exist so I used Preferences:Scheduling. It says to enable V3 Scheduling. It already was enabled. I pasted the code. It already had the learning and relearning set to less than 1 day in my main collection of decks.

I revised part of the code so that: const display_memory_state = true;

I quit and attempted to relaunch anki. It unexpectedly quit when I attempted to study a deck. My fault, I had forgotten to re-enable it. So, I re-launched anki, enabled the add-on, quit and re-launched. It crashed with the following error report:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-10.14.6-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2024-09-24 08:10:04
Add-ons possibly involved: ⁨FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 112, in on_future_done
  File "aqt.main", line 990, in on_collection_sync_finished
  File "_aqt.hooks", line 4595, in __call__
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 57, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids))
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 50, in auto_reschedule
    return fut.result()
  File "concurrent.futures._base", line 446, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 277, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 296, in reschedule_background
    deck_parameters = get_deck_parameters(custom_scheduler)
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/utils.py", line 234, in get_deck_parameters
    deck_parameters.items(), key=lambda item: item[0], reverse=True
UnboundLocalError: local variable 'deck_parameters' referenced before assignment

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 256, in on_done
    tooltip(f"{future.result()} in {time.time() - start_time:.2f} seconds")
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 112, in on_future_done
  File "aqt.main", line 990, in on_collection_sync_finished
  File "_aqt.hooks", line 4595, in __call__
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 57, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids))
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/sync_hook.py", line 50, in auto_reschedule
    return fut.result()
  File "concurrent.futures._base", line 446, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 277, in <lambda>
    lambda: reschedule_background(did, recent, filter_flag, filtered_cids),
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/schedule/reschedule.py", line 296, in reschedule_background
    deck_parameters = get_deck_parameters(custom_scheduler)
  File "/Users/kj/Library/Application Support/Anki2/addons21/759844606/utils.py", line 234, in get_deck_parameters
    deck_parameters.items(), key=lambda item: item[0], reverse=True
UnboundLocalError: local variable 'deck_parameters' referenced before assignment

**Comment by L-M-Sherlock** [comment]
Did you paste all the code into the Custom Scheduling field? I hope you can share the screenshot like https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/465#issuecomment-2366910265 again.

**Comment by L-M-Sherlock** [comment]
I guess you forget to include the version info:

<img width="526" alt="image" src="https://github.com/user-attachments/assets/37494b7f-4ffd-49bf-a949-f48b2e44f81f">

Please paste the full FSRS scheduler code into the Custom Scheduling field.
