### ISSUE TITLE
[BUG] easy_days sync crash

### ISSUE THREAD

**Issue by matejdro** [open-spaced-repetition/fsrs4anki-helper#470]
**Describe the bug**

Sync will error out with the following exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 142, in _on_closures_pending
    closure()
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 86, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 106, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.12/site-packages/aqt/sync.py", line 123, in on_future_done
    return on_done()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aqt/main.py", line 1058, in on_collection_sync_finished
    gui_hooks.sync_did_finish()
  File "/usr/lib/python3.12/site-packages/_aqt/hooks.py", line 5038, in __call__
    hook()
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 100, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 55, in auto_reschedule
    texts.append(fut.result())
                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 180, in <lambda>
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 214, in reschedule_background
    recent=False,
                  
  File "/home/matej/.local/share/Anki2/addons21/759844606/configuration.py", line 54, in easy_days
KeyError: 'easy_days'

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 142, in _on_closures_pending
    closure()
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 86, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 174, in on_done
    easy_specific_due_dates=[],
                          ^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 142, in _on_closures_pending
    closure()
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 86, in <lambda>
    lambda future: self.run_on_main(lambda: on_done(future))
                                            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aqt/taskman.py", line 106, in wrapped_done
    on_done(fut)
  File "/usr/lib/python3.12/site-packages/aqt/sync.py", line 123, in on_future_done
    return on_done()
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aqt/main.py", line 1058, in on_collection_sync_finished
    gui_hooks.sync_did_finish()
  File "/usr/lib/python3.12/site-packages/_aqt/hooks.py", line 5038, in __call__
    hook()
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 100, in <lambda>
    sync_did_finish.append(lambda: auto_reschedule(local_rids, texts))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/sync_hook.py", line 55, in auto_reschedule
    texts.append(fut.result())
                 ^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 180, in <lambda>
  File "/home/matej/.local/share/Anki2/addons21/759844606/schedule/reschedule.py", line 214, in reschedule_background
    recent=False,
                  
  File "/home/matej/.local/share/Anki2/addons21/759844606/configuration.py", line 54, in easy_days
KeyError: 'easy_days'
```

**To Reproduce**

I could only reproduce once using these steps

1. Have a synced collections between AnkiDroid and Anki desktop.
2. Make some changes on the phone
3. Sync on the desktop

**Expected behavior**

No sync error

**Screenshots**

**Environment**
 - Anki version: Anki 24.06.3 (d678e393) (src) (ao), Python 3.12.6 Qt 6.7.2 PyQt 6.7.1
 - FSRS Helper version `['759844606', 2024-09-25T08:18, 'None', mod]`
 - OS: Linux-6.10.10

**Additional context**

I'm not using easy_days feature at all, it is turned off completely.

**Comment by L-M-Sherlock** [comment]
Could you reinstall the add-on and try again?

**Comment by matejdro** [comment]
It does not happen anymore, even without reinstall, it only happened on one sync. I just wanted to report that this error can happen

**Comment by L-M-Sherlock** [comment]
I guess you update the add-on recently, right? It may update the configuration.json but not update the code in the first time.

**Comment by matejdro** [comment]
Yeah, addon updates pretty frequently, so it likely has updated.
