### ISSUE TITLE
[BUG] File "anki.decks", line 308, in config_dict_for_deck_id TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Korbells** [open-spaced-repetition/fsrs4anki-helper#494]
**Describe the bug**
When trying to use "reschedule all cards" an error pops up saying "An Anki encountered a problem. Please follow the troubleshooting steps.

Add-ons possibly involved: ⁨FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings⁩"

**To Reproduce**
1. Go to 'Tools'
2. Click on 'FSRS Helper'
3. Scroll down to 'Reschedule All Cards'

**Expected behavior**
All cards to be rescheduled
**Debug Info**
Anki 24.10 (23b7d636)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 144, in _on_closures_pending
  File "aqt.taskman", line 88, in <lambda>
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 243, in on_done
    finish_text = future.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 249, in <lambda>
    lambda: reschedule_background(
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 361, in reschedule_background
    for cid, did, _, desired_retention, maximum_interval in cards:
  File "C:\Users\NameAppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 351, in <lambda>
    fsrs.DM.config_dict_for_deck_id(x[1])["desiredRetention"],
  File "anki.decks", line 308, in config_dict_for_deck_id
TypeError: argument of type 'NoneType' is not iterable

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-15T04:46, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1771074083 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-09-06T01:58, 'None', '']
AnkiConnect ['2055492159', 2024-11-07T02:34, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-09-14T08:04, 'None', '']
Beautify-Anki 20 mizmu ['1116770498', 2023-10-31T19:51, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-10-04T04:54, 'None', mod]
Kimchi Reader Anki Addon ['1844914046', 2024-07-05T23:39, 'None', '']
Multiple Choice for Anki ['1566095810', 2023-11-17T21:59, 'None', mod]
anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ['858591644', 2024-08-10T04:15, 'None', '']

**Environment**
 - Anki version: [Version ⁨24.10 (23b7d636)⁩]
 - OS: [Windows]

**Comment by L-M-Sherlock** [comment]
Could you reproduce it in Anki 24.11?

**Comment by Korbells** [comment]
I tried it, the same error occurs.

Here is my collection. [collection-2024-11-16@11-59-05.zip](https://github.com/user-attachments/files/17784378/collection-2024-11-16%4011-59-05.zip)

Thank you for your support!

Here is the debug info:

Anki 24.11 (97e6b3d3)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 144, in _on_closures_pending
  File "aqt.taskman", line 88, in <lambda>
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 243, in on_done
    finish_text = future.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 249, in <lambda>
    lambda: reschedule_background(
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 361, in reschedule_background
    for cid, did, _, desired_retention, maximum_interval in cards:
  File "C:\Users\Name\AppData\Roaming\Anki2\addons21\759844606\schedule\reschedule.py", line 351, in <lambda>
    fsrs.DM.config_dict_for_deck_id(x[1])["desiredRetention"],
  File "anki.decks", line 308, in config_dict_for_deck_id
TypeError: argument of type 'NoneType' is not iterable

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-11-15T04:46, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1771074083 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-09-06T01:58, 'None', '']
AnkiConnect ['2055492159', 2024-11-07T02:34, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-09-14T08:04, 'None', '']
Beautify-Anki 20 mizmu ['1116770498', 2023-10-31T19:51, 'None', '']
HyperTTS - Add speech to y

our flashcards ['111623432', 2024-10-04T04:54, 'None', mod]
Kimchi Reader Anki Addon ['1844914046', 2024-07-05T23:39, 'None', '']
Multiple Choice for Anki ['1566095810', 2023-11-17T21:59, 'None', mod]
anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ['858591644', 2024-08-10T04:15, 'None', '']

**Comment by L-M-Sherlock** [comment]
<img width="799" alt="image" src="https://github.com/user-attachments/assets/49d99368-7f0c-4f25-965a-05ae26d65184">

You collection has a non-existent deck. Please check the database.

<img width="226" alt="image" src="https://github.com/user-attachments/assets/9c6c5fe5-203d-4928-be92-5411eed1f6b7">
