### ISSUE TITLE
Incompatibility with 2.1.56?

### ISSUE THREAD

**Issue by kylegoetz** [open-spaced-repetition/fsrs4anki-helper#7]
I've just installed the plugin and did "Reschedule cards in deck" and get this error from Anki:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-12.0.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-27 14:36:36
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/kylegoetz/Library/Application Support/Anki2/addons21/759844606/__init__.py", line 26, in <lambda>
    a.triggered.connect(lambda b, did=did: fun(did))
  File "/Users/kylegoetz/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 155, in reschedule
    again_ivl = next_interval(rescheduled_cards, retention, max_ivl)
  File "/Users/kylegoetz/Library/Application Support/Anki2/addons21/759844606/reschedule.py", line 39, in next_interval
    return min(max(int(round(math.log(retention) / math.log(0.9) * stability)), 1), max_ivl)
TypeError: unsupported operand type(s) for *: 'float' and 'set'

```

And here is the code pasted into the Custom Scheduling:

```javascript
// FSRS4Anki v3.9.6 Scheduler Qt6
set_version();
// The latest version will be released on https://github.com/open-spaced-repetition/fsrs4anki

var w = [0.3475, 0.744, 5.5054, -0.9453, -1.0023, 0.0151, 1.1452, -0.163, 0.5697, 1.6265, -0.5263, 0.7607, 0.9741];

// The above parameters can be optimized via FSRS4Anki optimizer.

// User's custom parameters for global
let requestRetention = 0.9; // recommended setting: 0.8 ~ 0.9
let maximumInterval = 36500;
let easyBonus = 1.3;
// [snip] nothing modified below this line at all
```

**Comment by kylegoetz** [comment]
It loks like reschedule.py line 39 is trying to multiply math.log(0.9), which is a float, by `stability`, which is a function argument. If you look back up in the code, the variable `reschedule` is passed in, and this is instantiated as `reschedule = set()`.

You can't multiply a set by a float.

**Comment by L-M-Sherlock** [comment]
My fault. I am fixing it.

**Comment by L-M-Sherlock** [comment]
Update and try it again.

**Comment by kylegoetz** [comment]
It worked. Freaking ugh, 500 additional cards to study beyond what I already did ;)
