### ISSUE TITLE
"IndexError: list index out of range" when rescheduling 

### ISSUE THREAD

**Issue by Vitorvlv** [open-spaced-repetition/fsrs4anki-helper#9]
```
Error

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed

If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.

When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.

Debug info
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
Platform: Linux-6.1.7-200.fc37.x86_64-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-31 21:41:00 
Add-ons possibly involved: ⁨FSRS4Anki Helper⁩

Caught exception
Traceback (most recent call last):
File "~home/.var/app/net.ankiweb.Anki/data/Anki2/addons21/759844606/__init__.py", line 15, in <lambda>
    action.triggered.connect(lambda b, did=None: fun(did)) 
File "~home/.var/app/net.ankiweb.Anki/data/Anki2/addons21/759844606/reschedule.py", line 50, in reschedule
skip_decks = get_skip_decks(custom_scheduler) if version[1] >= 12 else[]
File "~home/.var/app/net.ankiweb.Anki/data/Anki2/addons21/759844606/utils.py", line 49, in get_skip_decks
return list(map(lambda x: x.strip(']["'), re.findall(r'[const ]?skip_decks ?= ?(.*);', custom_scheduler)[0].split(', ')))
IndexError: list index out of range
```

values given by the optimizer:

```
    if (deck_name == "Medicina") {
        var w = [0.2809, 1.0081, 5.1204, -0.6659, -0.5897, 0.0402, 1.3742, -0.1968, 0.7698, 1.6818, -0.5114, 0.752, 0.5783];
    } else if (deck_name == "Medicina::Atual") {
        var w = [0.2809, 1.0081, 5.1204, -0.6659, -0.5897, 0.0402, 1.3742, -0.1968, 0.7698, 1.6818, -0.5114, 0.752, 0.5783];
        requestRetention = 0.9;
    } else if (deck_name.startsWith("Chinese")) {
        var w = [1.0004, 1.0133, 4.9492, -0.4562, -0.5011, 0.2189, 1.4571, -0.01, 0.8573, 1.9992, -0.2009, 0.5175, 1.0005];
    } else if (deck_name == "Geografia") {
        var w = [1.0004, 1.0133, 4.9492, -0.4562, -0.5011, 0.2189, 1.4571, -0.01, 0.8573, 1.9992, -0.2009, 0.5175, 1.0005];
    } else if (deck_name == "Vida pessoal") {
        requestRetention = 0.9;
    } else if (deck_name == "Programação") {
        var w = [1.0004, 1.0133, 4.9492, -0.4562, -0.5011, 0.2189, 1.4571, -0.01, 0.8573, 1.9992, -0.2009, 0.5175, 1.0005];
    } 
}
```

**Comment by Vitorvlv** [comment]
I guess in my sleepy state I must have done something wrong when inputing decks into the optimizer. Have just noticed that the last 4 decks all have the same values for w.

Did another run and now everything is working fine again. sorry!

**Comment by Vitorvlv** [comment]
Spoke too soon, sorry. The same error is still happening.

Current values given by the optimizer:

```
if (document.getElementById("deck") !== null) {
    const deck_name = document.getElementById("deck").getAttribute("deck_name");
    // parameters for a specific deck
    if (deck_name == "Medicina") {
        var w = [0.291, 1.0092, 5.1177, -0.6635, -0.5622, 0.0496, 1.3686, -0.1768, 0.7569, 1.6634, -0.5266, 0.7515, 0.5999];
        requestRetention = 0.84;
    } else if (deck_name == "Medicina::Atual") {
        var w = [0.291, 1.0092, 5.1177, -0.6635, -0.5622, 0.0496, 1.3686, -0.1768, 0.7569, 1.6634, -0.5266, 0.7515, 0.5999];
        requestRetention = 0.9;
    } else if (deck_name.startsWith("Chinese")) {
        var w = [0.9491, 0.9877, 5.137, -0.6223, -0.6712, 0.0007, 1.2838, -0.053, 0.6805, 1.7308, -0.4701, 0.4131, 0.8557];
        requestRetention = 0.86;
    } else if (deck_name == "Geografia") {
        var w = [0.8826, 1.0087, 5.2667, -0.8105, -0.7043, 0.0391, 1.2765, -0.1859, 0.6718, 1.5552, -0.6255, 0.8409, 0.4685];
    } else if (deck_name == "Vida pessoal") {
        var w = [0.9928, 1.0042, 5.0151, -0.5221, -0.5183, 0.1862, 1.3912, -0.0258, 0.7913, 1.9776, -0.2226, 0.4913, 0.9793]
        requestRetention = 1;
    } else if (deck_name == "Programação") {
        var w = [1.0028, 1.016, 4.958, -0.4732, -0.4913, 0.2174, 1.4466, -0.01, 0.8446, 2.0098, -0.1904, 0.5211, 1.0111];
    } 
}
```

**Comment by L-M-Sherlock** [comment]
Where are the default skip_decks?

**Comment by Vitorvlv** [comment]
oh, I didn't read the comments on the code, didn't realized you needed it even if you're not going to use it.

Just added and that fixed the issue, thanks!
